### ISSUE TITLE
Support for scripts to install Ubuntu 20.04 LTS (Focal Fossa)

### ISSUE THREAD

**Issue by aamcintosh** [xen-tools/xen-tools#63]
At the end of the discussion of Issue 51, foxxyz reports reports a problem trying to use xen-tools to build a Focal VM.  I cloned the master branch of the xen-tools repository, commit 79650b9d7052e961a4f0737bdbb702125d2ab5f0.  I copied everything from karmic into a new directory in /usr/share/xen-tools called focal.d and made the appropriate change in /etc/xen-tools.  I built a VM and booted it.  It died thus:
`
xc: error: panic: xc_dom_bzimageloader.c:768: xc_dom_probe_bzimage_kernel unable to LZ4 decompress kernel: Invalid kernel
xc: error: panic: xc_dom_core.c:702: xc_dom_find_loader: no loader found: Invalid kernel
libxl: error: libxl_dom.c:671:libxl__build_dom: xc_dom_parse_image failed: No such file or directory
libxl: error: libxl_create.c:1217:domcreate_rebuild_done: Domain 8:cannot (re-)build domain: -3
libxl: error: libxl_domain.c:1003:libxl__destroy_domid: Domain 8:Non-existant domain
libxl: error: libxl_domain.c:962:domain_destroy_callback: Domain 8:Unable to destroy guest
libxl: error: libxl_domain.c:889:domain_destroy_cb: Domain 8:Destruction of domain failed
`
I did this under bionic, using deboootstrap 1.0.95.  I see from the changelog that 1.0.110 is "recommended".  Could this be the cause of the problem?  I managed to get a successful install/boot for Bionic, but perhaps I was just lucky?

**Comment by aamcintosh** [comment]
Partial answer to my own question:  The resulting VM gets further.  Now running Ubuntu 20.04 on the host/build machine, which has debootstrap 1.0.118.  The kernel now oopses.  Output from oops attached.
[oops.txt](https://github.com/xen-tools/xen-tools/files/5465370/oops.txt)
(Sorry about ugly formatting in original question.  That wasn't the way git rendered it before I submitted.)

I'm now going to try installing latest tools from a git pull.

**Comment by aamcintosh** [comment]
That failed.
1)  Bogus complaints from make-orig-tar-gz about tabs in .git/hooks/fsmonitor-watchman.sample.  Fixed those.
2) make orig-tar-gz and dpkg-buildpackage can't agree on the name of the tar archive.  Former puts it in xen-tools_4.8.orig.tar.gz; latter wants xen-tools_4.8.1~dev.orig.tar.{bz2,gz,lzma,xz}.  Ran dpkg-buildpackage -uc -us -b instead.
3) Wiped out old package and installed this one.  Tried to build focal; got errors as in attached.
[oops2.txt](https://github.com/xen-tools/xen-tools/files/5465545/oops2.txt)
Resulting VM panics as in previous comment.

**Comment by aamcintosh** [comment]
I thought I would try the zip file instead of the git clone.  Got (different) errors as attached:
[oops3.txt](https://github.com/xen-tools/xen-tools/files/5465676/oops3.txt)  Also "make changelog" errors out because the source in the zip file doesn't speak git.  It's easily patched in the Makefile.  Correct solution is probably to touch ChangeLog so it exists, then run git and ignore any failure.

**Comment by aamcintosh** [comment]
I went back to the standard Ubuntu 20.04 version, and added a symlink for eoan.  I then build disco and eoan VMs.  disco worked fine, but eoan crashes in the same way as the others.  I'm willing to try a new version, but fixing this is above my paygrade.

**Comment by xtaran** [comment]
There is theoretical 20.04 support since commit 4ac4ae5987e79bdeaa4540a5ac41258415505c37 from 11th of Oct 2020 in the git repository. I also verified that it can bootstrap a 20.04 installation, but I haven't yet tested if it also can boot afterwards. Will check.

**Comment by werk21** [comment]
We created (and booted) guests with Ubuntu 18.04 and 20.04 on Dom0 with Ubuntu 18.04 and 20.04 without any problems. We use xen-tools with commit c0cb19eefcca1f2eb46ceff95896686e50ba774a. We use the latest stable version of xen.

**Comment by xtaran** [comment]
> There is theoretical 20.04 support since commit [4ac4ae5](https://github.com/xen-tools/xen-tools/commit/4ac4ae5987e79bdeaa4540a5ac41258415505c37) from 11th of Oct 2020 in the git repository. I also verified that it can bootstrap a 20.04 installation, but I haven't yet tested if it also can boot afterwards. Will check.

Checked: The test installation of 20.04 I did with `xen-tools` as of 58899daffe78f4749a20d937bac8eea6dc16e8a3 (only documentation and example changes since then to the current git HEAD at  af6ceacc4c9dcf3e12f8ce0d40d883c93dddf527) on Debian 10 Buster and `debootstrap 1.0.119~bpo10+1` booted up fine, had network connectivity and I could login on the console. The kernel which came up was `5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 x86_64`.

So in general, support for 20.04 is there and working.

Regarding your Oopses:

* `oops.txt:[    1.620764] Oops: 0000 [#1] SMP NOPTI`: Might be non-xen-related, at least [this looks similar](https://askubuntu.com/questions/1293945/20-10-complete-system-freeze-with-general-protection-fault-smp-nopti) and happened with a later kernel (5.8) on Ubuntu, too, but on a laptop.
* `oops2.txt`: Yeah, that failed early and with fanfares.
  1. `.git/hooks/fsmonitor-watchman.sample`: While this is a check of xen-tools which fails, the file in question is clearly not from xen-tools.
  2. Yeah, `dpkg-buildpackage -uc -us -b` is the right way for builds out of the midst of the git repo.
  3. Must admit, I have no idea at which stage that failed. Is that the whole log file? I'd assume the actual error was earlier and these are just follow-up errors.
* `oops3.txt`: Similar here. `/var/log/xen-tools/cosmicA.log` might contain hints about the actual cause. But it looks like something not being properly mounted or not properly unmounted on a previous run. This might be #55.

**Comment by xtaran** [comment]
Ah, please don't mind me closing this, but the general support for Ubuntu 20.04 Focal Fossa is definitely there.

If you continue to have issues, please feel free to open a new issue. Please include:

* host OS (Distribution + Release)
* installed debootstrap version
* installed {ubuntu,debian}-keying and/or {ubuntu,debian}-archive-keying versions. (Debian's ubuntu-keyring package is quite out of date and this can cause issues if `/etc/xen-tools/distributions.conf` is not uptodate.)
* xen-tools version or git commit ID
* full log file
* the actually used command, maybe anonymized for some options like actual IP addresses, passwords or so.
* if possible, the contents of `/etc/xen-tools/xen-tools.conf`, `/etc/xen-tools/distributions.conf` and the contents of the resulting `.cfg` file if it came that far.
